### ISSUE TITLE
对于示例中的preCheck

### ISSUE THREAD

**Issue by cplinux** [ShiningRush/fastflow#11]
看到示例中的是这样写的
```yaml
id: "test-dag"
name: "test"
vars:
  fileName:
    desc: "the file name"
    defaultValue: "file.txt"
tasks:
- id: "task1"
  actionName: "PrintAction"
  preCheck:
  - act: skip #you can set "skip" or "block"
    conditions:
    - source: vars # source could be "vars" or "share-data"
      key: "fileName"
      op: "in"
      values: ["warn.txt", "error.txt"]
```
preCheck应该是一个列表，但实际运行中发现，报错，查看代码得知，preCheck定义是一个PreChecks `map[string]*Check`对象，修改成
```yaml
    preCheck:
      act1:
        act: block
        conditions:
          - source: "vars"
            key: "fileName"
            op: "in"
            values: ["file.txt", "error.txt"]

```

如果是这样的话，不知道原意设计是有多个preCheck要处理，还是只能处理一个act的preCheck，然后再conditions里面设置多个条件判断呢？

按照我的理解，preCheck的定义应该是一个[]Check，能够根据多个条件来判断该节点是应该阻塞还是应该跳过
