### ISSUE TITLE
如何跳过一些路线的任务

### ISSUE THREAD

**Issue by 123cdxcc** [ShiningRush/fastflow#33]
如下图，我想在执行任务B时，如果条件命中了，跳过任务B，此时我希望任务E也能够跳过，这时候任务的线路是A->C->D，有点类似if-else，这种能够实现吗。

<img width="241" alt="image" src="https://github.com/ShiningRush/fastflow/assets/36818063/7ef242d5-c12e-45c4-a948-75c53ccef824">

**Comment by ShiningRush** [comment]
可以通过`PreCheck`来判断，`PreCheck`可以判断`ShareData` 中的值是否满足预期，如果满足则设置Task节点为 `Skip`，如果此时 E也需要跳过，保持任务E和任务B的 `Precheck`条件相同即可

**Comment by 123cdxcc** [comment]
谢谢解答，大概理解了这种场景。
我目前打算将fastflow用在流程引擎上，你能帮我看看我用在审批流上写的会签和或签的写法是不是正确的吗？
我感觉会签的写法好像有点别扭。

> 会签

``` 
  - id: "task-a"
    actionName: "approval-action"
    dependOn: ["begin"]
    params:
      123: "false" # key为用户ID
      456: "false" # key为用户ID
    preCheck:
      is123:
        act: block
        conditions:
          - source: "share-data"
            key: "123"
            op: "in"
            values: ["false"]
      is456:
        act: block
        conditions:
          - source: "share-data"
            key: "456"
            op: "in"
            values: [ "false" ]
```

> 或签
```
  - id: "task-b"
    actionName: "approval-action"
    dependOn: [ "task-b" ]
    params:
      uid: "" # 用户id
    preCheck:
      isApplyWait:
        act: block
        conditions:
          - source: "source-data"
            key: "uid"
            op: "not-in"
            values: [ "123", "456", "789" ]
      isApplyPass:
        act: skip
        conditions:
          - source: "share-data"
            key: "uid"
            op: "in"
            values: [ "123", "456", "789" ]
```
